_target_: hospitalizations.sim_hosps
sim_coefs:
  # these are the key predictors equal for all locations
  features:
    effectiveness:
      alerts_2wks: -0.1
      intercept: -5.0
    baseline:
      excess_heat_7d: 0.1
      weekend: 0.02
      intercept: -5.0

  # these is the effect on top of the feature
  confounders:
    effectiveness:
      intercept:
        log_med_hh_income: 0.05
        broadband_usage: 0.5        
    baseline:
      intercept:
        log_med_hh_income: -0.1
        log_pop_density: -0.1
      heat_qi:
        log_pop_density: 0.01
