# this is the conda requirements file for the env
name: weather2alert
channels:
  - conda-forge
  - pytorch
  # - nvidia  # uncomment if GPU/linux
dependencies:
  - python=3.10
  # - pytorch-cuda=12.1  # uncomment if GPU/linux
  - scipy
  - pip
  - tensorboardX
  - ipykernel
  - tqdm
  - pyarrow
  - tensordict
  - seaborn
  - pip:
    - pytorch-lightning
    - torch-tb-profiler
    - gym==0.17.2
    - stable-baselines3>=0.10.0
    - sb3-contrib
    - graphviz
    - statsmodels
    