census_api_key: ${oc.env:CENSUS_API_KEY}

data_dir: ../data

county_filter: 65000  # choose 'all' for no filter

heatmetrics:
  min_month: 5
  max_month: 9
  min_year: 2006
  max_year: 2019
  cols: ["HImin_C", "HImax_C", "HImean_C"]
  url: "https://ndownloader.figstatic.com/files/35070550"

confounders:
  county_shapefile: "https://www2.census.gov/geo/tiger/GENZ2013/cb_2013_us_county_500k.zip"

alerts:
  overwrite: false
  state: TX  # any state code
  significances: [A, W, Y]  # watch=A, warning=W, advisory=Y
  events: [EH, HT]  # , see https://www.weather.gov/media/vtec/VTEC_explanation2-23.pdf
  years: [2006, 2019]  # [ymin, ymax]
  download_wait: 60  # seconds 
  download_check_interval: 2  # seconds
  download_retries: 3
  headless: true  # otherwise use UI browser for scraping
  tz_map:
    C: "US/Central"
    CE: "US/Central"
    E: "US/Eastern"
    m: "MST"
    P: "US/Pacific"
    M: "US/Mountain"
    MP: "US/Mountain"
    CM: "US/Central"
    e: "EST"
    MC: "US/Mountain"

