defaults:
  - _self_
  - arch: nn
  - training: fast
  - hospitalizations: sim
  - constraints: mixed

data_dir: ../data

model:
  num_hidden_layers: ???
  hidden_dim: ???

name: ${hydra:runtime.choices.model}_${hydra:runtime.choices.training}_${hydra:runtime.choices.hospitalizations}

training:
  batch_size:   # leave empty it will be chose according to S and N
  epochs: ???
  gradient_clip_val: 1.0
  lr: 0.0003
  num_workers: 0
  num_particles: 1
  max_steps: -1  # no max steps
  jit: true
  accelerator: cpu

num_samples: 100
